[project]
name = "autograder"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "docker>=7.1.0",
    "pexpect>=4.9.0",
    "pydantic>=2.12.5",
    "tqdm>=4.67.1",
    "typer>=0.20.0",
]
